name: nue_ebook
description: A Flutter app for eBooks
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.1
  shared_preferences: ^0.5.10
  flutter_icons: ^1.1.0
  xml2json: ^4.3.0
  fluttertoast: ^7.0.2
  esys_flutter_share: ^1.0.2
  cached_network_image: ^2.2.0+1
  uuid: ^2.2.0
  objectdb: ^1.0.7+1
  epub_viewer: ^0.1.8
  path_provider: ^1.4.0
  dio: ^3.0.9
  permission_handler: ^4.2.0+hotfix.1
  google_fonts: ^1.1.0
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
